modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="zings_project_red_horn"
version="1.7.0"
displayName="ZiNG's Project Red-Horn"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="ZiNG! Studios"
description="A mod that adds Darling in the FranXX content"
enumExtensions="META-INF/enumextensions.json"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "zings_project_red_horn.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.zings_project_red_horn]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.95,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.zings_project_red_horn]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration