/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.zing.zingsprojectredhorn.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.event.BlockEntityTypeAddBlocksEvent;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.Block;
import net.minecraft.client.renderer.Sheets;

import com.zing.zingsprojectredhorn.block.*;
import com.zing.zingsprojectredhorn.ZingsProjectRedHornMod;

import java.util.function.Function;

@EventBusSubscriber
public class ZingsProjectRedHornModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(ZingsProjectRedHornMod.MODID);
	public static final DeferredBlock<Block> BLOCK_OF_ZERONIUM;
	public static final DeferredBlock<Block> BLOCK_OF_HIRONIUM;
	public static final DeferredBlock<Block> ZERONIUM_BRICKS;
	public static final DeferredBlock<Block> ZERONIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_ZERONIUM_ORE;
	public static final DeferredBlock<Block> HIRONIUM_BRICKS;
	public static final DeferredBlock<Block> HIRONIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_HIRONIUM_ORE;
	public static final DeferredBlock<Block> ZERO_TINTED_GLASS;
	public static final DeferredBlock<Block> ZERONIUM_BARS;
	public static final DeferredBlock<Block> ZERONIUM_TORCH;
	public static final DeferredBlock<Block> ZERONIUM_LANTERN;
	public static final DeferredBlock<Block> HIRO_TINTED_GLASS;
	public static final DeferredBlock<Block> HIRONIUM_BARS;
	public static final DeferredBlock<Block> HIRONIUM_TORCH;
	public static final DeferredBlock<Block> HIRONIUM_LANTERN;
	public static final DeferredBlock<Block> ZERONIUM_STAIRS;
	public static final DeferredBlock<Block> ZERONIUM_SLAB;
	public static final DeferredBlock<Block> ZERONIUM_WALL;
	public static final DeferredBlock<Block> HIRONIUM_STAIRS;
	public static final DeferredBlock<Block> HIRONIUM_SLAB;
	public static final DeferredBlock<Block> HIRONIUM_WALL;
	public static final DeferredBlock<Block> PLANTATION_BULB;
	public static final DeferredBlock<Block> PLANTATION_BULB_ON;
	public static final DeferredBlock<Block> ENCASED_SHELL_DECORATION;
	public static final DeferredBlock<Block> BOARDING_DOOR;
	public static final DeferredBlock<Block> BOARDING_GLASS;
	public static final DeferredBlock<Block> CHISELED_BOARDING_GLASS;
	public static final DeferredBlock<Block> BOARDING_BRICKS;
	public static final DeferredBlock<Block> YELLOW_LOUNGE_CLOTH;
	public static final DeferredBlock<Block> YELLOW_LOUNGE_CLOTH_SLAB;
	public static final DeferredBlock<Block> YELLOW_LOUNGE_CLOTH_STAIRS;
	public static final DeferredBlock<Block> CRACKED_BOARDING_GLASS;
	public static final DeferredBlock<Block> CHISELED_BOARDING_QUARTZ;
	public static final DeferredBlock<Block> BOARDING_CEILING_LAMP;
	public static final DeferredBlock<Block> BOARDING_CEILING_LAMP_ON;
	public static final DeferredBlock<Block> BOARDING_HOUSE_WHEEL_DECOR;
	public static final DeferredBlock<Block> BOARDING_HOUSE_CHAIR;
	public static final DeferredBlock<Block> BOARDING_HOUSE_VASE_OF_WHITE_ROSES;
	public static final DeferredBlock<Block> BOARDING_HOUSE_TABLE;
	public static final DeferredBlock<Block> BOARDING_HOUSE_GLASS_JAR;
	public static final DeferredBlock<Block> BOARDING_HOUSE_BOWL_OF_FRUITS;
	public static final DeferredBlock<Block> BOARDING_HOUSE_BATHROOM_SEAT;
	public static final DeferredBlock<Block> CHECKERED_QUARTZ_FLOOR;
	public static final DeferredBlock<Block> BOARDING_HOUSE_BATHROOM_BULB;
	public static final DeferredBlock<Block> BOARDING_HOUSE_DRAIN;
	public static final DeferredBlock<Block> BOARDING_HOUSE_BATHROOM_BULB_ON;
	public static final DeferredBlock<Block> TAPED_DOOR;
	public static final DeferredBlock<Block> VIRTUAL_GATE;
	public static final DeferredBlock<Block> BLOCKED_VIRTUAL_GATE;
	public static final DeferredBlock<Block> ACCEPT_VIRTUAL_GATE;
	public static final DeferredBlock<Block> STRELITZIA;
	public static final DeferredBlock<Block> DELPHINIUM;
	public static final DeferredBlock<Block> ARGENTEA;
	public static final DeferredBlock<Block> GENISTA;
	public static final DeferredBlock<Block> CHLOROPHYTUM;
	public static final DeferredBlock<Block> WHITE_ROSE_BUSH;
	public static final DeferredBlock<Block> BOARDING_HOUSE_VASE_OF_RED_ROSES;
	public static final DeferredBlock<Block> BOARDING_HOUSE_VASE_OF_BLUE_ROSES;
	public static final DeferredBlock<Block> ENCASED_BIRDZING_FEATHER_DECORATION;
	public static final DeferredBlock<Block> ENCASED_HORNED_BUTTERFLY_DECORATION;
	public static final DeferredBlock<Block> KLAXON_BONE_BLOCK;
	public static final DeferredBlock<Block> PARASITE_ROD;
	public static final DeferredBlock<Block> KLAXON_GOO_SPLAT;
	public static final DeferredBlock<Block> KLAXON_DETECTOR;
	public static final DeferredBlock<Block> MAGMA_ENERGY_FUEL_BLOCK;
	public static final DeferredBlock<Block> KLAXON_TURRET;
	public static final DeferredBlock<Block> CERASUS_FLOOR;
	public static final DeferredBlock<Block> CERASUS_FLOOR_LINE;
	public static final DeferredBlock<Block> SNOW_OAK_LEAVES;
	public static final DeferredBlock<Block> SNOW_OAK_PLANKS;
	public static final DeferredBlock<Block> SNOW_OAK_WOOD;
	public static final DeferredBlock<Block> SNOW_OAK_LOG;
	public static final DeferredBlock<Block> PLAYROOM_FLOOR_TILES;
	public static final DeferredBlock<Block> TESTING_TABLE;
	public static final DeferredBlock<Block> ABANDONED_JUKEBOX;
	public static final DeferredBlock<Block> ABADONED_CHISELED_BOOKSHELF;
	public static final DeferredBlock<Block> PRISMAX;
	public static final DeferredBlock<Block> WARP_GATE;
	public static final DeferredBlock<Block> THE_BEAST_AND_THE_PRINCE_BOOK;
	public static final DeferredBlock<Block> GREENHOUSE_LAMP;
	public static final DeferredBlock<Block> GREENHOUSE_LAMP_ON;
	public static final DeferredBlock<Block> CHISELED_ZERONIUM;
	public static final DeferredBlock<Block> CHISELED_HIRONIUM;
	public static final DeferredBlock<Block> HIRONIUM_LADDER;
	public static final DeferredBlock<Block> ZERONIUM_LADDER;
	public static final DeferredBlock<Block> ZERONIUM_TILES;
	public static final DeferredBlock<Block> HIRONIUM_TILES;
	public static final DeferredBlock<Block> DARLING_RED_WOOL;
	public static final DeferredBlock<Block> DARLING_BLUE_WOOL;
	public static final DeferredBlock<Block> BLOCK_OF_ICHIGONIUM;
	public static final DeferredBlock<Block> ICHIGONIUM_BRICKS;
	public static final DeferredBlock<Block> ICHIGONIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_ICHIGONIUM_ORE;
	public static final DeferredBlock<Block> ICHIGO_TINTED_GLASS;
	public static final DeferredBlock<Block> ICHIGONIUM_BARS;
	public static final DeferredBlock<Block> ICHIGONIUM_TORCH;
	public static final DeferredBlock<Block> ICHIGONIUM_LANTERN;
	public static final DeferredBlock<Block> ICHIGONIUM_STAIRS;
	public static final DeferredBlock<Block> ICHIGONIUM_SLAB;
	public static final DeferredBlock<Block> ICHIGONIUM_WALL;
	public static final DeferredBlock<Block> ICHIGONIUM_LADDER;
	public static final DeferredBlock<Block> ICHIGONIUM_TILES;
	public static final DeferredBlock<Block> ONIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_ONIUM_ORE;
	public static final DeferredBlock<Block> ZERO_CRYSTAL;
	public static final DeferredBlock<Block> HIRO_CRYSTAL;
	public static final DeferredBlock<Block> ICHIGO_CRYSTAL;
	public static final DeferredBlock<Block> STRIPPED_POPLARAX_LOG;
	public static final DeferredBlock<Block> POPLARAX_LOG;
	public static final DeferredBlock<Block> POPLARAX_PLANKS;
	public static final DeferredBlock<Block> POPLARAX_SLAB;
	public static final DeferredBlock<Block> POPLARAX_STAIRS;
	public static final DeferredBlock<Block> POPLARAX_FENCE;
	public static final DeferredBlock<Block> POPLARAX_FENCE_GATE;
	public static final DeferredBlock<Block> POPLARAX_BUTTON;
	public static final DeferredBlock<Block> POPLARAX_PRESSURE_PLATE;
	public static final DeferredBlock<Block> POPLARAX_DOOR;
	public static final DeferredBlock<Block> POPLARAX_TRAPDOOR;
	public static final DeferredBlock<Block> POPLARAX_SIGN;
	public static final DeferredBlock<Block> POPLARAX_WALL_SIGN;
	public static final DeferredBlock<Block> BLUE_POPLARAX_LEAVES;
	public static final DeferredBlock<Block> INDIGO_POPLARAX_LEAVES;
	public static final DeferredBlock<Block> PURPLE_POPLARAX_LEAVES;
	public static final DeferredBlock<Block> POPLARAX_SAPLING;
	public static final DeferredBlock<Block> STRIPPED_FERROROCK_WILLOW_LOG;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_LOG;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_PLANKS;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_SLAB;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_STAIRS;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_FENCE;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_FENCE_GATE;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_BUTTON;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_PRESSURE_PLATE;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_DOOR;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_TRAPDOOR;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_SIGN;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_WALL_SIGN;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_LEAVES;
	public static final DeferredBlock<Block> FERROROCK_WILLOW_SAPLING;
	public static final DeferredBlock<Block> STRIPPED_ZERO_PLATEA_LOG;
	public static final DeferredBlock<Block> ZERO_PLATEA_LOG;
	public static final DeferredBlock<Block> ZERO_PLATEA_PLANKS;
	public static final DeferredBlock<Block> ZERO_PLATEA_SLAB;
	public static final DeferredBlock<Block> ZERO_PLATEA_STAIRS;
	public static final DeferredBlock<Block> ZERO_PLATEA_FENCE;
	public static final DeferredBlock<Block> ZERO_PLATEA_FENCE_GATE;
	public static final DeferredBlock<Block> ZERO_PLATEA_BUTTON;
	public static final DeferredBlock<Block> ZERO_PLATEA_PRESSURE_PLATE;
	public static final DeferredBlock<Block> ZERO_PLATEA_DOOR;
	public static final DeferredBlock<Block> ZERO_PLATEA_TRAPDOOR;
	public static final DeferredBlock<Block> ZERO_PLATEA_SIGN;
	public static final DeferredBlock<Block> ZERO_PLATEA_WALL_SIGN;
	public static final DeferredBlock<Block> ZERO_PLATEA_LEAVES;
	public static final DeferredBlock<Block> XENONIC_SULFUR;
	public static final DeferredBlock<Block> DRAGONRAGE_FERN;
	public static final DeferredBlock<Block> XENONIC_SULFUR_DIAMOND_ORE;
	public static final DeferredBlock<Block> BLUE_OBSIDIAN;
	public static final DeferredBlock<Block> FERROUS_MINT_MOSS;
	public static final DeferredBlock<Block> GUTEN_CORAL;
	public static final DeferredBlock<Block> GUTEN_CORAL_BLOCK;
	public static final DeferredBlock<Block> XENON_PORTAL;
	static {
		BLOCK_OF_ZERONIUM = register("block_of_zeronium", BlockOfZeroniumBlock::new);
		BLOCK_OF_HIRONIUM = register("block_of_hironium", BlockOfHironiumBlock::new);
		ZERONIUM_BRICKS = register("zeronium_bricks", ZeroniumBricksBlock::new);
		ZERONIUM_ORE = register("zeronium_ore", ZeroniumOreBlock::new);
		DEEPSLATE_ZERONIUM_ORE = register("deepslate_zeronium_ore", DeepslateZeroniumOreBlock::new);
		HIRONIUM_BRICKS = register("hironium_bricks", HironiumBricksBlock::new);
		HIRONIUM_ORE = register("hironium_ore", HironiumOreBlock::new);
		DEEPSLATE_HIRONIUM_ORE = register("deepslate_hironium_ore", DeepslateHironiumOreBlock::new);
		ZERO_TINTED_GLASS = register("zero_tinted_glass", ZeroTintedGlassBlock::new);
		ZERONIUM_BARS = register("zeronium_bars", ZeroniumBarsBlock::new);
		ZERONIUM_TORCH = register("zeronium_torch", ZeroniumTorchBlock::new);
		ZERONIUM_LANTERN = register("zeronium_lantern", ZeroniumLanternBlock::new);
		HIRO_TINTED_GLASS = register("hiro_tinted_glass", HiroTintedGlassBlock::new);
		HIRONIUM_BARS = register("hironium_bars", HironiumBarsBlock::new);
		HIRONIUM_TORCH = register("hironium_torch", HironiumTorchBlock::new);
		HIRONIUM_LANTERN = register("hironium_lantern", HironiumLanternBlock::new);
		ZERONIUM_STAIRS = register("zeronium_stairs", ZeroniumStairsBlock::new);
		ZERONIUM_SLAB = register("zeronium_slab", ZeroniumSlabBlock::new);
		ZERONIUM_WALL = register("zeronium_wall", ZeroniumWallBlock::new);
		HIRONIUM_STAIRS = register("hironium_stairs", HironiumStairsBlock::new);
		HIRONIUM_SLAB = register("hironium_slab", HironiumSlabBlock::new);
		HIRONIUM_WALL = register("hironium_wall", HironiumWallBlock::new);
		PLANTATION_BULB = register("plantation_bulb", PlantationBulbBlock::new);
		PLANTATION_BULB_ON = register("plantation_bulb_on", PlantationBulbOnBlock::new);
		ENCASED_SHELL_DECORATION = register("encased_shell_decoration", EncasedShellDecorationBlock::new);
		BOARDING_DOOR = register("boarding_door", BoardingDoorBlock::new);
		BOARDING_GLASS = register("boarding_glass", BoardingGlassBlock::new);
		CHISELED_BOARDING_GLASS = register("chiseled_boarding_glass", ChiseledBoardingGlassBlock::new);
		BOARDING_BRICKS = register("boarding_bricks", BoardingBricksBlock::new);
		YELLOW_LOUNGE_CLOTH = register("yellow_lounge_cloth", YellowLoungeClothBlock::new);
		YELLOW_LOUNGE_CLOTH_SLAB = register("yellow_lounge_cloth_slab", YellowLoungeClothSlabBlock::new);
		YELLOW_LOUNGE_CLOTH_STAIRS = register("yellow_lounge_cloth_stairs", YellowLoungeClothStairsBlock::new);
		CRACKED_BOARDING_GLASS = register("cracked_boarding_glass", CrackedBoardingGlassBlock::new);
		CHISELED_BOARDING_QUARTZ = register("chiseled_boarding_quartz", ChiseledBoardingQuartzBlock::new);
		BOARDING_CEILING_LAMP = register("boarding_ceiling_lamp", BoardingCeilingLampBlock::new);
		BOARDING_CEILING_LAMP_ON = register("boarding_ceiling_lamp_on", BoardingCeilingLampOnBlock::new);
		BOARDING_HOUSE_WHEEL_DECOR = register("boarding_house_wheel_decor", BoardingHouseWheelDecorBlock::new);
		BOARDING_HOUSE_CHAIR = register("boarding_house_chair", BoardingHouseChairBlock::new);
		BOARDING_HOUSE_VASE_OF_WHITE_ROSES = register("boarding_house_vase_of_white_roses", BoardingHouseVaseOfWhiteRosesBlock::new);
		BOARDING_HOUSE_TABLE = register("boarding_house_table", BoardingHouseTableBlock::new);
		BOARDING_HOUSE_GLASS_JAR = register("boarding_house_glass_jar", BoardingHouseGlassJarBlock::new);
		BOARDING_HOUSE_BOWL_OF_FRUITS = register("boarding_house_bowl_of_fruits", BoardingHouseBowlOfFruitsBlock::new);
		BOARDING_HOUSE_BATHROOM_SEAT = register("boarding_house_bathroom_seat", BoardingHouseBathroomSeatBlock::new);
		CHECKERED_QUARTZ_FLOOR = register("checkered_quartz_floor", CheckeredQuartzFloorBlock::new);
		BOARDING_HOUSE_BATHROOM_BULB = register("boarding_house_bathroom_bulb", BoardingHouseBathroomBulbBlock::new);
		BOARDING_HOUSE_DRAIN = register("boarding_house_drain", BoardingHouseDrainBlock::new);
		BOARDING_HOUSE_BATHROOM_BULB_ON = register("boarding_house_bathroom_bulb_on", BoardingHouseBathroomBulbOnBlock::new);
		TAPED_DOOR = register("taped_door", TapedDoorBlock::new);
		VIRTUAL_GATE = register("virtual_gate", VirtualGateBlock::new);
		BLOCKED_VIRTUAL_GATE = register("blocked_virtual_gate", BlockedVirtualGateBlock::new);
		ACCEPT_VIRTUAL_GATE = register("accept_virtual_gate", AcceptVirtualGateBlock::new);
		STRELITZIA = register("strelitzia", StrelitziaBlock::new);
		DELPHINIUM = register("delphinium", DelphiniumBlock::new);
		ARGENTEA = register("argentea", ArgenteaBlock::new);
		GENISTA = register("genista", GenistaBlock::new);
		CHLOROPHYTUM = register("chlorophytum", ChlorophytumBlock::new);
		WHITE_ROSE_BUSH = register("white_rose_bush", WhiteRoseBushBlock::new);
		BOARDING_HOUSE_VASE_OF_RED_ROSES = register("boarding_house_vase_of_red_roses", BoardingHouseVaseOfRedRosesBlock::new);
		BOARDING_HOUSE_VASE_OF_BLUE_ROSES = register("boarding_house_vase_of_blue_roses", BoardingHouseVaseOfBlueRosesBlock::new);
		ENCASED_BIRDZING_FEATHER_DECORATION = register("encased_birdzing_feather_decoration", EncasedBirdzingFeatherDecorationBlock::new);
		ENCASED_HORNED_BUTTERFLY_DECORATION = register("encased_horned_butterfly_decoration", EncasedHornedButterflyDecorationBlock::new);
		KLAXON_BONE_BLOCK = register("klaxon_bone_block", KlaxonBoneBlockBlock::new);
		PARASITE_ROD = register("parasite_rod", ParasiteRodBlock::new);
		KLAXON_GOO_SPLAT = register("klaxon_goo_splat", KlaxonGooSplatBlock::new);
		KLAXON_DETECTOR = register("klaxon_detector", KlaxonDetectorBlock::new);
		MAGMA_ENERGY_FUEL_BLOCK = register("magma_energy_fuel_block", MagmaEnergyFuelBlockBlock::new);
		KLAXON_TURRET = register("klaxon_turret", KlaxonTurretBlock::new);
		CERASUS_FLOOR = register("cerasus_floor", CerasusFloorBlock::new);
		CERASUS_FLOOR_LINE = register("cerasus_floor_line", CerasusFloorLineBlock::new);
		SNOW_OAK_LEAVES = register("snow_oak_leaves", SnowOakLeavesBlock::new);
		SNOW_OAK_PLANKS = register("snow_oak_planks", SnowOakPlanksBlock::new);
		SNOW_OAK_WOOD = register("snow_oak_wood", SnowOakWoodBlock::new);
		SNOW_OAK_LOG = register("snow_oak_log", SnowOakLogBlock::new);
		PLAYROOM_FLOOR_TILES = register("playroom_floor_tiles", PlayroomFloorTilesBlock::new);
		TESTING_TABLE = register("testing_table", TestingTableBlock::new);
		ABANDONED_JUKEBOX = register("abandoned_jukebox", AbandonedJukeboxBlock::new);
		ABADONED_CHISELED_BOOKSHELF = register("abadoned_chiseled_bookshelf", AbadonedChiseledBookshelfBlock::new);
		PRISMAX = register("prismax", PrismaxBlock::new);
		WARP_GATE = register("warp_gate", WarpGateBlock::new);
		THE_BEAST_AND_THE_PRINCE_BOOK = register("the_beast_and_the_prince_book", TheBeastAndThePrinceBookBlock::new);
		GREENHOUSE_LAMP = register("greenhouse_lamp", GreenhouseLampBlock::new);
		GREENHOUSE_LAMP_ON = register("greenhouse_lamp_on", GreenhouseLampOnBlock::new);
		CHISELED_ZERONIUM = register("chiseled_zeronium", ChiseledZeroniumBlock::new);
		CHISELED_HIRONIUM = register("chiseled_hironium", ChiseledHironiumBlock::new);
		HIRONIUM_LADDER = register("hironium_ladder", HironiumLadderBlock::new);
		ZERONIUM_LADDER = register("zeronium_ladder", ZeroniumLadderBlock::new);
		ZERONIUM_TILES = register("zeronium_tiles", ZeroniumTilesBlock::new);
		HIRONIUM_TILES = register("hironium_tiles", HironiumTilesBlock::new);
		DARLING_RED_WOOL = register("darling_red_wool", DarlingRedWoolBlock::new);
		DARLING_BLUE_WOOL = register("darling_blue_wool", DarlingBlueWoolBlock::new);
		BLOCK_OF_ICHIGONIUM = register("block_of_ichigonium", BlockOfIchigoniumBlock::new);
		ICHIGONIUM_BRICKS = register("ichigonium_bricks", IchigoniumBricksBlock::new);
		ICHIGONIUM_ORE = register("ichigonium_ore", IchigoniumOreBlock::new);
		DEEPSLATE_ICHIGONIUM_ORE = register("deepslate_ichigonium_ore", DeepslateIchigoniumOreBlock::new);
		ICHIGO_TINTED_GLASS = register("ichigo_tinted_glass", IchigoTintedGlassBlock::new);
		ICHIGONIUM_BARS = register("ichigonium_bars", IchigoniumBarsBlock::new);
		ICHIGONIUM_TORCH = register("ichigonium_torch", IchigoniumTorchBlock::new);
		ICHIGONIUM_LANTERN = register("ichigonium_lantern", IchigoniumLanternBlock::new);
		ICHIGONIUM_STAIRS = register("ichigonium_stairs", IchigoniumStairsBlock::new);
		ICHIGONIUM_SLAB = register("ichigonium_slab", IchigoniumSlabBlock::new);
		ICHIGONIUM_WALL = register("ichigonium_wall", IchigoniumWallBlock::new);
		ICHIGONIUM_LADDER = register("ichigonium_ladder", IchigoniumLadderBlock::new);
		ICHIGONIUM_TILES = register("ichigonium_tiles", IchigoniumTilesBlock::new);
		ONIUM_ORE = register("onium_ore", OniumOreBlock::new);
		DEEPSLATE_ONIUM_ORE = register("deepslate_onium_ore", DeepslateOniumOreBlock::new);
		ZERO_CRYSTAL = register("zero_crystal", ZeroCrystalBlock::new);
		HIRO_CRYSTAL = register("hiro_crystal", HiroCrystalBlock::new);
		ICHIGO_CRYSTAL = register("ichigo_crystal", IchigoCrystalBlock::new);
		STRIPPED_POPLARAX_LOG = register("stripped_poplarax_log", StrippedPoplaraxLogBlock::new);
		POPLARAX_LOG = register("poplarax_log", PoplaraxLogBlock::new);
		POPLARAX_PLANKS = register("poplarax_planks", PoplaraxPlanksBlock::new);
		POPLARAX_SLAB = register("poplarax_slab", PoplaraxSlabBlock::new);
		POPLARAX_STAIRS = register("poplarax_stairs", PoplaraxStairsBlock::new);
		POPLARAX_FENCE = register("poplarax_fence", PoplaraxFenceBlock::new);
		POPLARAX_FENCE_GATE = register("poplarax_fence_gate", PoplaraxFenceGateBlock::new);
		POPLARAX_BUTTON = register("poplarax_button", PoplaraxButtonBlock::new);
		POPLARAX_PRESSURE_PLATE = register("poplarax_pressure_plate", PoplaraxPressurePlateBlock::new);
		POPLARAX_DOOR = register("poplarax_door", PoplaraxDoorBlock::new);
		POPLARAX_TRAPDOOR = register("poplarax_trapdoor", PoplaraxTrapdoorBlock::new);
		POPLARAX_SIGN = register("poplarax_sign", PoplaraxSignBlock::new);
		POPLARAX_WALL_SIGN = register("poplarax_wall_sign", PoplaraxWallSignBlock::new);
		BLUE_POPLARAX_LEAVES = register("blue_poplarax_leaves", BluePoplaraxLeavesBlock::new);
		INDIGO_POPLARAX_LEAVES = register("indigo_poplarax_leaves", IndigoPoplaraxLeavesBlock::new);
		PURPLE_POPLARAX_LEAVES = register("purple_poplarax_leaves", PurplePoplaraxLeavesBlock::new);
		POPLARAX_SAPLING = register("poplarax_sapling", PoplaraxSaplingBlock::new);
		STRIPPED_FERROROCK_WILLOW_LOG = register("stripped_ferrorock_willow_log", StrippedFerrorockWillowLogBlock::new);
		FERROROCK_WILLOW_LOG = register("ferrorock_willow_log", FerrorockWillowLogBlock::new);
		FERROROCK_WILLOW_PLANKS = register("ferrorock_willow_planks", FerrorockWillowPlanksBlock::new);
		FERROROCK_WILLOW_SLAB = register("ferrorock_willow_slab", FerrorockWillowSlabBlock::new);
		FERROROCK_WILLOW_STAIRS = register("ferrorock_willow_stairs", FerrorockWillowStairsBlock::new);
		FERROROCK_WILLOW_FENCE = register("ferrorock_willow_fence", FerrorockWillowFenceBlock::new);
		FERROROCK_WILLOW_FENCE_GATE = register("ferrorock_willow_fence_gate", FerrorockWillowFenceGateBlock::new);
		FERROROCK_WILLOW_BUTTON = register("ferrorock_willow_button", FerrorockWillowButtonBlock::new);
		FERROROCK_WILLOW_PRESSURE_PLATE = register("ferrorock_willow_pressure_plate", FerrorockWillowPressurePlateBlock::new);
		FERROROCK_WILLOW_DOOR = register("ferrorock_willow_door", FerrorockWillowDoorBlock::new);
		FERROROCK_WILLOW_TRAPDOOR = register("ferrorock_willow_trapdoor", FerrorockWillowTrapdoorBlock::new);
		FERROROCK_WILLOW_SIGN = register("ferrorock_willow_sign", FerrorockWillowSignBlock::new);
		FERROROCK_WILLOW_WALL_SIGN = register("ferrorock_willow_wall_sign", FerrorockWillowWallSignBlock::new);
		FERROROCK_WILLOW_LEAVES = register("ferrorock_willow_leaves", FerrorockWillowLeavesBlock::new);
		FERROROCK_WILLOW_SAPLING = register("ferrorock_willow_sapling", FerrorockWillowSaplingBlock::new);
		STRIPPED_ZERO_PLATEA_LOG = register("stripped_zero_platea_log", StrippedZeroPlateaLogBlock::new);
		ZERO_PLATEA_LOG = register("zero_platea_log", ZeroPlateaLogBlock::new);
		ZERO_PLATEA_PLANKS = register("zero_platea_planks", ZeroPlateaPlanksBlock::new);
		ZERO_PLATEA_SLAB = register("zero_platea_slab", ZeroPlateaSlabBlock::new);
		ZERO_PLATEA_STAIRS = register("zero_platea_stairs", ZeroPlateaStairsBlock::new);
		ZERO_PLATEA_FENCE = register("zero_platea_fence", ZeroPlateaFenceBlock::new);
		ZERO_PLATEA_FENCE_GATE = register("zero_platea_fence_gate", ZeroPlateaFenceGateBlock::new);
		ZERO_PLATEA_BUTTON = register("zero_platea_button", ZeroPlateaButtonBlock::new);
		ZERO_PLATEA_PRESSURE_PLATE = register("zero_platea_pressure_plate", ZeroPlateaPressurePlateBlock::new);
		ZERO_PLATEA_DOOR = register("zero_platea_door", ZeroPlateaDoorBlock::new);
		ZERO_PLATEA_TRAPDOOR = register("zero_platea_trapdoor", ZeroPlateaTrapdoorBlock::new);
		ZERO_PLATEA_SIGN = register("zero_platea_sign", ZeroPlateaSignBlock::new);
		ZERO_PLATEA_WALL_SIGN = register("zero_platea_wall_sign", ZeroPlateaWallSignBlock::new);
		ZERO_PLATEA_LEAVES = register("zero_platea_leaves", ZeroPlateaLeavesBlock::new);
		XENONIC_SULFUR = register("xenonic_sulfur", XenonicSulfurBlock::new);
		DRAGONRAGE_FERN = register("dragonrage_fern", DragonrageFernBlock::new);
		XENONIC_SULFUR_DIAMOND_ORE = register("xenonic_sulfur_diamond_ore", XenonicSulfurDiamondOreBlock::new);
		BLUE_OBSIDIAN = register("blue_obsidian", BlueObsidianBlock::new);
		FERROUS_MINT_MOSS = register("ferrous_mint_moss", FerrousMintMossBlock::new);
		GUTEN_CORAL = register("guten_coral", GutenCoralBlock::new);
		GUTEN_CORAL_BLOCK = register("guten_coral_block", GutenCoralBlockBlock::new);
		XENON_PORTAL = register("xenon_portal", XenonPortalBlock::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
		return REGISTRY.registerBlock(name, supplier);
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.BlockTintSources event) {
			DragonrageFernBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void clientSetup(FMLClientSetupEvent event) {
			Sheets.addWoodType(ZingsProjectRedHornModWoodTypes.POPLARAX_SIGN_WOOD_TYPE);
			Sheets.addWoodType(ZingsProjectRedHornModWoodTypes.FERROROCK_WILLOW_SIGN_WOOD_TYPE);
			Sheets.addWoodType(ZingsProjectRedHornModWoodTypes.ZERO_PLATEA_SIGN_WOOD_TYPE);
		}
	}

	@SubscribeEvent
	public static void registerSigns(BlockEntityTypeAddBlocksEvent event) {
		event.modify(BlockEntityType.SIGN, POPLARAX_SIGN.get(), POPLARAX_WALL_SIGN.get());
		event.modify(BlockEntityType.SIGN, FERROROCK_WILLOW_SIGN.get(), FERROROCK_WILLOW_WALL_SIGN.get());
		event.modify(BlockEntityType.SIGN, ZERO_PLATEA_SIGN.get(), ZERO_PLATEA_WALL_SIGN.get());
	}
}