package net.mcreator.zingsprojectredhorn.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.*;

import net.mcreator.zingsprojectredhorn.item.*;
import net.mcreator.zingsprojectredhorn.block.PlantationBulbOnBlock;
import net.mcreator.zingsprojectredhorn.ZingsProjectRedHornMod;

import java.util.function.Function;

public class ZingsProjectRedHornModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(ZingsProjectRedHornMod.MODID);
	public static final DeferredItem<Item> ZERO_TWO_SPAWN_EGG;
	public static final DeferredItem<Item> KLAXON_ZAP;
	public static final DeferredItem<Item> ZERONIUM;
	public static final DeferredItem<Item> ZERONIUM_INGOT;
	public static final DeferredItem<Item> HIRONIUM;
	public static final DeferredItem<Item> HIRONIUM_INGOT;
	public static final DeferredItem<Item> ZERONIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> ZERONIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ZERONIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ZERONIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> HIRONIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> HIRONIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> HIRONIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> HIRONIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> ZERONIUM_SWORD;
	public static final DeferredItem<Item> HIRONIUM_SWORD;
	public static final DeferredItem<Item> ZERONIUM_AXE;
	public static final DeferredItem<Item> ZERONIUM_HOE;
	public static final DeferredItem<Item> ZERONIUM_SHOVEL;
	public static final DeferredItem<Item> ZERONIUM_PICKAXE;
	public static final DeferredItem<Item> HIRONIUM_AXE;
	public static final DeferredItem<Item> HIRONIUM_HOE;
	public static final DeferredItem<Item> HIRONIUM_SHOVEL;
	public static final DeferredItem<Item> HIRONIUM_PICKAXE;
	public static final DeferredItem<Item> BLOCK_OF_ZERONIUM;
	public static final DeferredItem<Item> BLOCK_OF_HIRONIUM;
	public static final DeferredItem<Item> ZERONIUM_BRICKS;
	public static final DeferredItem<Item> ZERONIUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_ZERONIUM_ORE;
	public static final DeferredItem<Item> HIRONIUM_BRICKS;
	public static final DeferredItem<Item> HIRONIUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_HIRONIUM_ORE;
	public static final DeferredItem<Item> ZERO_TINTED_GLASS;
	public static final DeferredItem<Item> ZERONIUM_BARS;
	public static final DeferredItem<Item> ZERONIUM_TORCH;
	public static final DeferredItem<Item> ZERONIUM_LANTERN;
	public static final DeferredItem<Item> HIRO_TINTED_GLASS;
	public static final DeferredItem<Item> HIRONIUM_BARS;
	public static final DeferredItem<Item> HIRONIUM_TORCH;
	public static final DeferredItem<Item> HIRONIUM_LANTERN;
	public static final DeferredItem<Item> ZERONIUM_STAIRS;
	public static final DeferredItem<Item> ZERONIUM_SLAB;
	public static final DeferredItem<Item> ZERONIUM_WALL;
	public static final DeferredItem<Item> HIRONIUM_STAIRS;
	public static final DeferredItem<Item> HIRONIUM_SLAB;
	public static final DeferredItem<Item> HIRONIUM_WALL;
	public static final DeferredItem<Item> HORN_SHEARS;
	public static final DeferredItem<Item> HIRO_SPAWN_EGG;
	public static final DeferredItem<Item> PLANTATION_BULB;
	public static final DeferredItem<Item> PLANTATION_BULB_ON;
	public static final DeferredItem<Item> ENCASED_SHELL_DECORATION;
	public static final DeferredItem<Item> BOARDING_DOOR;
	public static final DeferredItem<Item> BOARDING_GLASS;
	public static final DeferredItem<Item> CHISELED_BOARDING_GLASS;
	public static final DeferredItem<Item> BOARDING_BRICKS;
	public static final DeferredItem<Item> YELLOW_LOUNGE_CLOTH;
	public static final DeferredItem<Item> YELLOW_LOUNGE_CLOTH_SLAB;
	public static final DeferredItem<Item> YELLOW_LOUNGE_CLOTH_STAIRS;
	public static final DeferredItem<Item> CRACKED_BOARDING_GLASS;
	public static final DeferredItem<Item> CHISELED_BOARDING_QUARTZ;
	public static final DeferredItem<Item> BOARDING_CEILING_LAMP;
	public static final DeferredItem<Item> BOARDING_CEILING_LAMP_ON;
	public static final DeferredItem<Item> BOARDING_HOUSE_WHEEL_DECOR;
	public static final DeferredItem<Item> BOARDING_HOUSE_CHAIR;
	public static final DeferredItem<Item> BOARDING_HOUSE_VASE_OF_WHITE_ROSES;
	public static final DeferredItem<Item> BOARDING_HOUSE_TABLE;
	public static final DeferredItem<Item> BOARDING_HOUSE_GLASS_JAR;
	public static final DeferredItem<Item> BOARDING_HOUSE_BOWL_OF_FRUITS;
	public static final DeferredItem<Item> BOARDING_HOUSE_BATHROOM_SEAT;
	public static final DeferredItem<Item> CHECKERED_QUARTZ_FLOOR;
	public static final DeferredItem<Item> BOARDING_HOUSE_BATHROOM_BULB;
	public static final DeferredItem<Item> BOARDING_HOUSE_DRAIN;
	public static final DeferredItem<Item> BOARDING_HOUSE_BATHROOM_BULB_ON;
	public static final DeferredItem<Item> TAPED_DOOR;
	public static final DeferredItem<Item> HONEY_RAW_BEEF;
	public static final DeferredItem<Item> HONEY_RAW_MUTTON;
	public static final DeferredItem<Item> HONEY_RAW_PORKCHOP;
	public static final DeferredItem<Item> CLASS_ID;
	public static final DeferredItem<Item> VIRTUAL_GATE;
	public static final DeferredItem<Item> BLOCKED_VIRTUAL_GATE;
	public static final DeferredItem<Item> ACCEPT_VIRTUAL_GATE;
	public static final DeferredItem<Item> ZERONIUM_HORN_FRAGMENT;
	public static final DeferredItem<Item> HIRONIUM_HORN_FRAGMENT;
	public static final DeferredItem<Item> PARASITE_ARROW;
	public static final DeferredItem<Item> PARASITE_CROSSBOW_MELEE;
	public static final DeferredItem<Item> PARASITE_CROSSBOW_RANGED;
	public static final DeferredItem<Item> PARASITE_STAFF;
	public static final DeferredItem<Item> PARASITE_BOW;
	public static final DeferredItem<Item> MASKED_VINDICATOR_SPAWN_EGG;
	public static final DeferredItem<Item> MASKED_VILLAGER_SPAWN_EGG;
	public static final DeferredItem<Item> MASKED_PILLAGER_SPAWN_EGG;
	public static final DeferredItem<Item> MASKED_ILLUSIONER_SPAWN_EGG;
	public static final DeferredItem<Item> MEEKONI_SPAWN_EGG;
	public static final DeferredItem<Item> KLAXON_BIRDZING_SPAWN_EGG;
	public static final DeferredItem<Item> STRELITZIA;
	public static final DeferredItem<Item> DELPHINIUM;
	public static final DeferredItem<Item> ARGENTEA;
	public static final DeferredItem<Item> GENISTA;
	public static final DeferredItem<Item> CHLOROPHYTUM;
	public static final DeferredItem<Item> WHITE_ROSE_BUSH;
	public static final DeferredItem<Item> BOARDING_HOUSE_VASE_OF_RED_ROSES;
	public static final DeferredItem<Item> BOARDING_HOUSE_VASE_OF_BLUE_ROSES;
	public static final DeferredItem<Item> XX_BANNER_PATTERN;
	public static final DeferredItem<Item> DISC_WINGS;
	public static final DeferredItem<Item> DISC_MY_DARLING;
	public static final DeferredItem<Item> DISC_HORNS;
	public static final DeferredItem<Item> ENCASED_BIRDZING_FEATHER_DECORATION;
	public static final DeferredItem<Item> ENCASED_HORNED_BUTTERFLY_DECORATION;
	public static final DeferredItem<Item> KLAXON_BLAZE_ROD;
	public static final DeferredItem<Item> PRISMAX_SHARD;
	public static final DeferredItem<Item> TOTEM_OF_IMMUNITY;
	public static final DeferredItem<Item> KLAXON_BLAZE_POWDER;
	public static final DeferredItem<Item> FERMENTED_KLAXON_SPIDER_EYE;
	public static final DeferredItem<Item> ZING_BOOK_VOLUME_FOUR;
	public static final DeferredItem<Item> KLAXON_BONE_BLOCK;
	public static final DeferredItem<Item> PARASITE_ROD;
	public static final DeferredItem<Item> BLOB_OF_KLAXON;
	public static final DeferredItem<Item> KLAXON_GOO_SPLAT;
	public static final DeferredItem<Item> KLAXOSAUR_DNA;
	public static final DeferredItem<Item> ZERO_TWOS_LIMITER;
	public static final DeferredItem<Item> GLASS_PIECE;
	public static final DeferredItem<Item> KLAXON_DETECTOR;
	public static final DeferredItem<Item> MAGMA_ENERGY_FUEL_BLOCK;
	public static final DeferredItem<Item> KLAXON_TURRET;
	public static final DeferredItem<Item> CERASUS_FLOOR;
	public static final DeferredItem<Item> CERASUS_FLOOR_LINE;
	public static final DeferredItem<Item> KLAXON_CREEPER_SPAWN_EGG;
	public static final DeferredItem<Item> KLAXON_ZOMBIE_SPAWN_EGG;
	public static final DeferredItem<Item> KLAXON_SPIDER_SPAWN_EGG;
	public static final DeferredItem<Item> KLAXON_SKELETON_SPAWN_EGG;
	public static final DeferredItem<Item> SNOW_OAK_LEAVES;
	public static final DeferredItem<Item> SNOW_OAK_PLANKS;
	public static final DeferredItem<Item> SNOW_OAK_WOOD;
	public static final DeferredItem<Item> SNOW_OAK_LOG;
	public static final DeferredItem<Item> PLAYROOM_FLOOR_TILES;
	public static final DeferredItem<Item> TESTING_TABLE;
	public static final DeferredItem<Item> SOULESS_ZERO_TWO_SPAWN_EGG;
	public static final DeferredItem<Item> SOUL_OF_ZERO_TWO_SPAWN_EGG;
	public static final DeferredItem<Item> ABANDONED_JUKEBOX;
	public static final DeferredItem<Item> ABADONED_CHISELED_BOOKSHELF;
	public static final DeferredItem<Item> PRISMAX;
	public static final DeferredItem<Item> WARP_GATE;
	public static final DeferredItem<Item> JIAN_BANNER_PATTERN;
	public static final DeferredItem<Item> SOUL_OF_HIRO_SPAWN_EGG;
	public static final DeferredItem<Item> SOULESS_HIRO_SPAWN_EGG;
	public static final DeferredItem<Item> ZERO_THREE_SPAWN_EGG;
	public static final DeferredItem<Item> ZERO_FOUR_SPAWN_EGG;
	public static final DeferredItem<Item> THE_BEAST_AND_THE_PRINCE_BOOK;
	public static final DeferredItem<Item> GREENHOUSE_LAMP;
	public static final DeferredItem<Item> GREENHOUSE_LAMP_ON;
	public static final DeferredItem<Item> CHISELED_ZERONIUM;
	public static final DeferredItem<Item> CHISELED_HIRONIUM;
	public static final DeferredItem<Item> HIRONIUM_LADDER;
	public static final DeferredItem<Item> ZERONIUM_LADDER;
	public static final DeferredItem<Item> ZERONIUM_TILES;
	public static final DeferredItem<Item> HIRONIUM_TILES;
	public static final DeferredItem<Item> CHLOROPHYTUM_PURPLE_DYE;
	public static final DeferredItem<Item> ARGENTEA_PINK_DYE;
	public static final DeferredItem<Item> GENISTA_GREEN_DYE;
	public static final DeferredItem<Item> DELPHINIUM_BLUE_DYE;
	public static final DeferredItem<Item> STRELITZIA_RED_DYE;
	public static final DeferredItem<Item> DARLING_BLUE_DYE;
	public static final DeferredItem<Item> DARLING_RED_DYE;
	public static final DeferredItem<Item> DARLING_RED_WOOL;
	public static final DeferredItem<Item> DARLING_BLUE_WOOL;
	public static final DeferredItem<Item> ICHIGONIUM;
	public static final DeferredItem<Item> ICHIGONIUM_INGOT;
	public static final DeferredItem<Item> ICHIGONIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> ICHIGONIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ICHIGONIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ICHIGONIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> ICHIGONIUM_SWORD;
	public static final DeferredItem<Item> ICHIGONIUM_AXE;
	public static final DeferredItem<Item> ICHIGONIUM_HOE;
	public static final DeferredItem<Item> ICHIGONIUM_SHOVEL;
	public static final DeferredItem<Item> ICHIGONIUM_PICKAXE;
	public static final DeferredItem<Item> BLOCK_OF_ICHIGONIUM;
	public static final DeferredItem<Item> ICHIGONIUM_BRICKS;
	public static final DeferredItem<Item> ICHIGONIUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_ICHIGONIUM_ORE;
	public static final DeferredItem<Item> ICHIGO_TINTED_GLASS;
	public static final DeferredItem<Item> ICHIGONIUM_BARS;
	public static final DeferredItem<Item> ICHIGONIUM_TORCH;
	public static final DeferredItem<Item> ICHIGONIUM_LANTERN;
	public static final DeferredItem<Item> ICHIGONIUM_STAIRS;
	public static final DeferredItem<Item> ICHIGONIUM_SLAB;
	public static final DeferredItem<Item> ICHIGONIUM_WALL;
	public static final DeferredItem<Item> ICHIGONIUM_HORN_FRAGMENT;
	public static final DeferredItem<Item> ICHIGONIUM_LADDER;
	public static final DeferredItem<Item> ICHIGONIUM_TILES;
	public static final DeferredItem<Item> ICHIGO_SPAWN_EGG;
	public static final DeferredItem<Item> ZERO_ARMOR_TRIM_SMITHING_TABLE;
	public static final DeferredItem<Item> ZERO_TWO_HEADBAND;
	public static final DeferredItem<Item> ONIUM;
	public static final DeferredItem<Item> ONIUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_ONIUM_ORE;
	public static final DeferredItem<Item> ZERO_CRYSTAL;
	public static final DeferredItem<Item> HIRO_CRYSTAL;
	public static final DeferredItem<Item> ICHIGO_CRYSTAL;
	public static final DeferredItem<Item> DRAGONRAGE_BERRY;
	public static final DeferredItem<Item> TOXIC_DRAGONRAGE_BERRY;
	public static final DeferredItem<Item> DIAMOND_DRAGONRAGE_BERRY;
	public static final DeferredItem<Item> FERROUS_MINT_SUGAR;
	public static final DeferredItem<Item> FERROUS_MINT_DYE;
	public static final DeferredItem<Item> STRIPPED_POPLARAX_LOG;
	public static final DeferredItem<Item> POPLARAX_LOG;
	public static final DeferredItem<Item> POPLARAX_PLANKS;
	public static final DeferredItem<Item> POPLARAX_SLAB;
	public static final DeferredItem<Item> POPLARAX_STAIRS;
	public static final DeferredItem<Item> POPLARAX_FENCE;
	public static final DeferredItem<Item> POPLARAX_FENCE_GATE;
	public static final DeferredItem<Item> POPLARAX_BUTTON;
	public static final DeferredItem<Item> POPLARAX_PRESSURE_PLATE;
	public static final DeferredItem<Item> POPLARAX_DOOR;
	public static final DeferredItem<Item> POPLARAX_TRAPDOOR;
	public static final DeferredItem<Item> POPLARAX_SIGN;
	public static final DeferredItem<Item> BLUE_POPLARAX_LEAVES;
	public static final DeferredItem<Item> INDIGO_POPLARAX_LEAVES;
	public static final DeferredItem<Item> PURPLE_POPLARAX_LEAVES;
	public static final DeferredItem<Item> POPLARAX_SAPLING;
	public static final DeferredItem<Item> STRIPPED_FERROROCK_WILLOW_LOG;
	public static final DeferredItem<Item> FERROROCK_WILLOW_LOG;
	public static final DeferredItem<Item> FERROROCK_WILLOW_PLANKS;
	public static final DeferredItem<Item> FERROROCK_WILLOW_SLAB;
	public static final DeferredItem<Item> FERROROCK_WILLOW_STAIRS;
	public static final DeferredItem<Item> FERROROCK_WILLOW_FENCE;
	public static final DeferredItem<Item> FERROROCK_WILLOW_FENCE_GATE;
	public static final DeferredItem<Item> FERROROCK_WILLOW_BUTTON;
	public static final DeferredItem<Item> FERROROCK_WILLOW_PRESSURE_PLATE;
	public static final DeferredItem<Item> FERROROCK_WILLOW_DOOR;
	public static final DeferredItem<Item> FERROROCK_WILLOW_TRAPDOOR;
	public static final DeferredItem<Item> FERROROCK_WILLOW_SIGN;
	public static final DeferredItem<Item> FERROROCK_WILLOW_BOAT;
	public static final DeferredItem<Item> FERROROCK_WILLOW_BOAT_WITH_CHEST;
	public static final DeferredItem<Item> FERROROCK_WILLOW_LEAVES;
	public static final DeferredItem<Item> FERROROCK_WILLOW_SAPLING;
	public static final DeferredItem<Item> STRIPPED_ZERO_PLATEA_LOG;
	public static final DeferredItem<Item> ZERO_PLATEA_LOG;
	public static final DeferredItem<Item> ZERO_PLATEA_PLANKS;
	public static final DeferredItem<Item> ZERO_PLATEA_SLAB;
	public static final DeferredItem<Item> ZERO_PLATEA_STAIRS;
	public static final DeferredItem<Item> ZERO_PLATEA_FENCE;
	public static final DeferredItem<Item> ZERO_PLATEA_FENCE_GATE;
	public static final DeferredItem<Item> ZERO_PLATEA_BUTTON;
	public static final DeferredItem<Item> ZERO_PLATEA_PRESSURE_PLATE;
	public static final DeferredItem<Item> ZERO_PLATEA_DOOR;
	public static final DeferredItem<Item> ZERO_PLATEA_TRAPDOOR;
	public static final DeferredItem<Item> ZERO_PLATEA_SIGN;
	public static final DeferredItem<Item> ZERO_PLATEA_RAFT;
	public static final DeferredItem<Item> ZERO_PLATEA_RAFT_WITH_CHEST;
	public static final DeferredItem<Item> ZERO_PLATEA_LEAVES;
	public static final DeferredItem<Item> XENONIC_SULFUR;
	public static final DeferredItem<Item> DRAGONRAGE_FERN;
	public static final DeferredItem<Item> XENONIC_SULFUR_DIAMOND_ORE;
	public static final DeferredItem<Item> BLUE_OBSIDIAN;
	public static final DeferredItem<Item> FERROUS_MINT_MOSS;
	public static final DeferredItem<Item> GUTEN_CORAL;
	public static final DeferredItem<Item> GUTEN_CORAL_BLOCK;
	public static final DeferredItem<Item> XENON;
	static {
		ZERO_TWO_SPAWN_EGG = register("zero_two_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.ZERO_TWO.get())));
		KLAXON_ZAP = register("klaxon_zap", KlaxonZapItem::new);
		ZERONIUM = register("zeronium", ZeroniumItem::new);
		ZERONIUM_INGOT = register("zeronium_ingot", ZeroniumIngotItem::new);
		HIRONIUM = register("hironium", HironiumItem::new);
		HIRONIUM_INGOT = register("hironium_ingot", HironiumIngotItem::new);
		ZERONIUM_ARMOR_HELMET = register("zeronium_armor_helmet", ZeroniumArmorItem.Helmet::new);
		ZERONIUM_ARMOR_CHESTPLATE = register("zeronium_armor_chestplate", ZeroniumArmorItem.Chestplate::new);
		ZERONIUM_ARMOR_LEGGINGS = register("zeronium_armor_leggings", ZeroniumArmorItem.Leggings::new);
		ZERONIUM_ARMOR_BOOTS = register("zeronium_armor_boots", ZeroniumArmorItem.Boots::new);
		HIRONIUM_ARMOR_HELMET = register("hironium_armor_helmet", HironiumArmorItem.Helmet::new);
		HIRONIUM_ARMOR_CHESTPLATE = register("hironium_armor_chestplate", HironiumArmorItem.Chestplate::new);
		HIRONIUM_ARMOR_LEGGINGS = register("hironium_armor_leggings", HironiumArmorItem.Leggings::new);
		HIRONIUM_ARMOR_BOOTS = register("hironium_armor_boots", HironiumArmorItem.Boots::new);
		ZERONIUM_SWORD = register("zeronium_sword", ZeroniumSwordItem::new);
		HIRONIUM_SWORD = register("hironium_sword", HironiumSwordItem::new);
		ZERONIUM_AXE = register("zeronium_axe", ZeroniumAxeItem::new);
		ZERONIUM_HOE = register("zeronium_hoe", ZeroniumHoeItem::new);
		ZERONIUM_SHOVEL = register("zeronium_shovel", ZeroniumShovelItem::new);
		ZERONIUM_PICKAXE = register("zeronium_pickaxe", ZeroniumPickaxeItem::new);
		HIRONIUM_AXE = register("hironium_axe", HironiumAxeItem::new);
		HIRONIUM_HOE = register("hironium_hoe", HironiumHoeItem::new);
		HIRONIUM_SHOVEL = register("hironium_shovel", HironiumShovelItem::new);
		HIRONIUM_PICKAXE = register("hironium_pickaxe", HironiumPickaxeItem::new);
		BLOCK_OF_ZERONIUM = block(ZingsProjectRedHornModBlocks.BLOCK_OF_ZERONIUM, new Item.Properties().fireResistant());
		BLOCK_OF_HIRONIUM = block(ZingsProjectRedHornModBlocks.BLOCK_OF_HIRONIUM, new Item.Properties().fireResistant());
		ZERONIUM_BRICKS = block(ZingsProjectRedHornModBlocks.ZERONIUM_BRICKS);
		ZERONIUM_ORE = block(ZingsProjectRedHornModBlocks.ZERONIUM_ORE);
		DEEPSLATE_ZERONIUM_ORE = block(ZingsProjectRedHornModBlocks.DEEPSLATE_ZERONIUM_ORE);
		HIRONIUM_BRICKS = block(ZingsProjectRedHornModBlocks.HIRONIUM_BRICKS);
		HIRONIUM_ORE = block(ZingsProjectRedHornModBlocks.HIRONIUM_ORE);
		DEEPSLATE_HIRONIUM_ORE = block(ZingsProjectRedHornModBlocks.DEEPSLATE_HIRONIUM_ORE);
		ZERO_TINTED_GLASS = block(ZingsProjectRedHornModBlocks.ZERO_TINTED_GLASS);
		ZERONIUM_BARS = block(ZingsProjectRedHornModBlocks.ZERONIUM_BARS);
		ZERONIUM_TORCH = block(ZingsProjectRedHornModBlocks.ZERONIUM_TORCH);
		ZERONIUM_LANTERN = block(ZingsProjectRedHornModBlocks.ZERONIUM_LANTERN);
		HIRO_TINTED_GLASS = block(ZingsProjectRedHornModBlocks.HIRO_TINTED_GLASS);
		HIRONIUM_BARS = block(ZingsProjectRedHornModBlocks.HIRONIUM_BARS);
		HIRONIUM_TORCH = block(ZingsProjectRedHornModBlocks.HIRONIUM_TORCH);
		HIRONIUM_LANTERN = block(ZingsProjectRedHornModBlocks.HIRONIUM_LANTERN);
		ZERONIUM_STAIRS = block(ZingsProjectRedHornModBlocks.ZERONIUM_STAIRS);
		ZERONIUM_SLAB = block(ZingsProjectRedHornModBlocks.ZERONIUM_SLAB);
		ZERONIUM_WALL = block(ZingsProjectRedHornModBlocks.ZERONIUM_WALL);
		HIRONIUM_STAIRS = block(ZingsProjectRedHornModBlocks.HIRONIUM_STAIRS);
		HIRONIUM_SLAB = block(ZingsProjectRedHornModBlocks.HIRONIUM_SLAB);
		HIRONIUM_WALL = block(ZingsProjectRedHornModBlocks.HIRONIUM_WALL);
		HORN_SHEARS = register("horn_shears", HornShearsItem::new);
		HIRO_SPAWN_EGG = register("hiro_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.HIRO.get())));
		PLANTATION_BULB = block(ZingsProjectRedHornModBlocks.PLANTATION_BULB);
		PLANTATION_BULB_ON = register("plantation_bulb_on", PlantationBulbOnBlock.Item::new);
		ENCASED_SHELL_DECORATION = block(ZingsProjectRedHornModBlocks.ENCASED_SHELL_DECORATION);
		BOARDING_DOOR = doubleBlock(ZingsProjectRedHornModBlocks.BOARDING_DOOR);
		BOARDING_GLASS = block(ZingsProjectRedHornModBlocks.BOARDING_GLASS);
		CHISELED_BOARDING_GLASS = block(ZingsProjectRedHornModBlocks.CHISELED_BOARDING_GLASS);
		BOARDING_BRICKS = block(ZingsProjectRedHornModBlocks.BOARDING_BRICKS);
		YELLOW_LOUNGE_CLOTH = block(ZingsProjectRedHornModBlocks.YELLOW_LOUNGE_CLOTH);
		YELLOW_LOUNGE_CLOTH_SLAB = block(ZingsProjectRedHornModBlocks.YELLOW_LOUNGE_CLOTH_SLAB);
		YELLOW_LOUNGE_CLOTH_STAIRS = block(ZingsProjectRedHornModBlocks.YELLOW_LOUNGE_CLOTH_STAIRS);
		CRACKED_BOARDING_GLASS = block(ZingsProjectRedHornModBlocks.CRACKED_BOARDING_GLASS);
		CHISELED_BOARDING_QUARTZ = block(ZingsProjectRedHornModBlocks.CHISELED_BOARDING_QUARTZ);
		BOARDING_CEILING_LAMP = block(ZingsProjectRedHornModBlocks.BOARDING_CEILING_LAMP);
		BOARDING_CEILING_LAMP_ON = block(ZingsProjectRedHornModBlocks.BOARDING_CEILING_LAMP_ON);
		BOARDING_HOUSE_WHEEL_DECOR = block(ZingsProjectRedHornModBlocks.BOARDING_HOUSE_WHEEL_DECOR);
		BOARDING_HOUSE_CHAIR = block(ZingsProjectRedHornModBlocks.BOARDING_HOUSE_CHAIR);
		BOARDING_HOUSE_VASE_OF_WHITE_ROSES = block(ZingsProjectRedHornModBlocks.BOARDING_HOUSE_VASE_OF_WHITE_ROSES);
		BOARDING_HOUSE_TABLE = block(ZingsProjectRedHornModBlocks.BOARDING_HOUSE_TABLE);
		BOARDING_HOUSE_GLASS_JAR = block(ZingsProjectRedHornModBlocks.BOARDING_HOUSE_GLASS_JAR);
		BOARDING_HOUSE_BOWL_OF_FRUITS = block(ZingsProjectRedHornModBlocks.BOARDING_HOUSE_BOWL_OF_FRUITS);
		BOARDING_HOUSE_BATHROOM_SEAT = block(ZingsProjectRedHornModBlocks.BOARDING_HOUSE_BATHROOM_SEAT);
		CHECKERED_QUARTZ_FLOOR = block(ZingsProjectRedHornModBlocks.CHECKERED_QUARTZ_FLOOR);
		BOARDING_HOUSE_BATHROOM_BULB = block(ZingsProjectRedHornModBlocks.BOARDING_HOUSE_BATHROOM_BULB);
		BOARDING_HOUSE_DRAIN = block(ZingsProjectRedHornModBlocks.BOARDING_HOUSE_DRAIN);
		BOARDING_HOUSE_BATHROOM_BULB_ON = block(ZingsProjectRedHornModBlocks.BOARDING_HOUSE_BATHROOM_BULB_ON);
		TAPED_DOOR = doubleBlock(ZingsProjectRedHornModBlocks.TAPED_DOOR);
		HONEY_RAW_BEEF = register("honey_raw_beef", HoneyRawBeefItem::new);
		HONEY_RAW_MUTTON = register("honey_raw_mutton", HoneyRawMuttonItem::new);
		HONEY_RAW_PORKCHOP = register("honey_raw_porkchop", HoneyRawPorkchopItem::new);
		CLASS_ID = register("class_id", ClassIDItem::new);
		VIRTUAL_GATE = block(ZingsProjectRedHornModBlocks.VIRTUAL_GATE);
		BLOCKED_VIRTUAL_GATE = block(ZingsProjectRedHornModBlocks.BLOCKED_VIRTUAL_GATE);
		ACCEPT_VIRTUAL_GATE = block(ZingsProjectRedHornModBlocks.ACCEPT_VIRTUAL_GATE);
		ZERONIUM_HORN_FRAGMENT = register("zeronium_horn_fragment", ZeroniumHornFragmentItem::new);
		HIRONIUM_HORN_FRAGMENT = register("hironium_horn_fragment", HironiumHornFragmentItem::new);
		PARASITE_ARROW = register("parasite_arrow", ParasiteArrowItem::new);
		PARASITE_CROSSBOW_MELEE = register("parasite_crossbow_melee", ParasiteCrossbowMeleeItem::new);
		PARASITE_CROSSBOW_RANGED = register("parasite_crossbow_ranged", ParasiteCrossbowRangedItem::new);
		PARASITE_STAFF = register("parasite_staff", ParasiteStaffItem::new);
		PARASITE_BOW = register("parasite_bow", ParasiteBowItem::new);
		MASKED_VINDICATOR_SPAWN_EGG = register("masked_vindicator_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.MASKED_VINDICATOR.get())));
		MASKED_VILLAGER_SPAWN_EGG = register("masked_villager_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.MASKED_VILLAGER.get())));
		MASKED_PILLAGER_SPAWN_EGG = register("masked_pillager_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.MASKED_PILLAGER.get())));
		MASKED_ILLUSIONER_SPAWN_EGG = register("masked_illusioner_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.MASKED_ILLUSIONER.get())));
		MEEKONI_SPAWN_EGG = register("meekoni_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.MEEKONI.get())));
		KLAXON_BIRDZING_SPAWN_EGG = register("klaxon_birdzing_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.KLAXON_BIRDZING.get())));
		STRELITZIA = block(ZingsProjectRedHornModBlocks.STRELITZIA);
		DELPHINIUM = block(ZingsProjectRedHornModBlocks.DELPHINIUM);
		ARGENTEA = block(ZingsProjectRedHornModBlocks.ARGENTEA);
		GENISTA = block(ZingsProjectRedHornModBlocks.GENISTA);
		CHLOROPHYTUM = block(ZingsProjectRedHornModBlocks.CHLOROPHYTUM);
		WHITE_ROSE_BUSH = doubleBlock(ZingsProjectRedHornModBlocks.WHITE_ROSE_BUSH);
		BOARDING_HOUSE_VASE_OF_RED_ROSES = block(ZingsProjectRedHornModBlocks.BOARDING_HOUSE_VASE_OF_RED_ROSES, new Item.Properties().rarity(Rarity.UNCOMMON));
		BOARDING_HOUSE_VASE_OF_BLUE_ROSES = block(ZingsProjectRedHornModBlocks.BOARDING_HOUSE_VASE_OF_BLUE_ROSES, new Item.Properties().rarity(Rarity.RARE));
		XX_BANNER_PATTERN = register("xx_banner_pattern", XXBannerPatternItem::new);
		DISC_WINGS = register("disc_wings", DiscWingsItem::new);
		DISC_MY_DARLING = register("disc_my_darling", DiscMyDarlingItem::new);
		DISC_HORNS = register("disc_horns", DiscHornsItem::new);
		ENCASED_BIRDZING_FEATHER_DECORATION = block(ZingsProjectRedHornModBlocks.ENCASED_BIRDZING_FEATHER_DECORATION);
		ENCASED_HORNED_BUTTERFLY_DECORATION = block(ZingsProjectRedHornModBlocks.ENCASED_HORNED_BUTTERFLY_DECORATION);
		KLAXON_BLAZE_ROD = register("klaxon_blaze_rod", KlaxonBlazeRodItem::new);
		PRISMAX_SHARD = register("prismax_shard", PrismaxShardItem::new);
		TOTEM_OF_IMMUNITY = register("totem_of_immunity", TotemOfImmunityItem::new);
		KLAXON_BLAZE_POWDER = register("klaxon_blaze_powder", KlaxonBlazePowderItem::new);
		FERMENTED_KLAXON_SPIDER_EYE = register("fermented_klaxon_spider_eye", FermentedKlaxonSpiderEyeItem::new);
		ZING_BOOK_VOLUME_FOUR = register("zing_book_volume_four", ZingBookVolumeFourItem::new);
		KLAXON_BONE_BLOCK = block(ZingsProjectRedHornModBlocks.KLAXON_BONE_BLOCK);
		PARASITE_ROD = block(ZingsProjectRedHornModBlocks.PARASITE_ROD);
		BLOB_OF_KLAXON = register("blob_of_klaxon", BlobOfKlaxonItem::new);
		KLAXON_GOO_SPLAT = block(ZingsProjectRedHornModBlocks.KLAXON_GOO_SPLAT, new Item.Properties().rarity(Rarity.RARE));
		KLAXOSAUR_DNA = register("klaxosaur_dna", KlaxosaurDNAItem::new);
		ZERO_TWOS_LIMITER = register("zero_twos_limiter", ZeroTwosLimiterItem::new);
		GLASS_PIECE = register("glass_piece", GlassPieceItem::new);
		KLAXON_DETECTOR = block(ZingsProjectRedHornModBlocks.KLAXON_DETECTOR);
		MAGMA_ENERGY_FUEL_BLOCK = block(ZingsProjectRedHornModBlocks.MAGMA_ENERGY_FUEL_BLOCK);
		KLAXON_TURRET = block(ZingsProjectRedHornModBlocks.KLAXON_TURRET);
		CERASUS_FLOOR = block(ZingsProjectRedHornModBlocks.CERASUS_FLOOR);
		CERASUS_FLOOR_LINE = block(ZingsProjectRedHornModBlocks.CERASUS_FLOOR_LINE);
		KLAXON_CREEPER_SPAWN_EGG = register("klaxon_creeper_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.KLAXON_CREEPER.get())));
		KLAXON_ZOMBIE_SPAWN_EGG = register("klaxon_zombie_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.KLAXON_ZOMBIE.get())));
		KLAXON_SPIDER_SPAWN_EGG = register("klaxon_spider_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.KLAXON_SPIDER.get())));
		KLAXON_SKELETON_SPAWN_EGG = register("klaxon_skeleton_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.KLAXON_SKELETON.get())));
		SNOW_OAK_LEAVES = block(ZingsProjectRedHornModBlocks.SNOW_OAK_LEAVES);
		SNOW_OAK_PLANKS = block(ZingsProjectRedHornModBlocks.SNOW_OAK_PLANKS);
		SNOW_OAK_WOOD = block(ZingsProjectRedHornModBlocks.SNOW_OAK_WOOD);
		SNOW_OAK_LOG = block(ZingsProjectRedHornModBlocks.SNOW_OAK_LOG);
		PLAYROOM_FLOOR_TILES = block(ZingsProjectRedHornModBlocks.PLAYROOM_FLOOR_TILES);
		TESTING_TABLE = block(ZingsProjectRedHornModBlocks.TESTING_TABLE);
		SOULESS_ZERO_TWO_SPAWN_EGG = register("souless_zero_two_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.SOULESS_ZERO_TWO.get())));
		SOUL_OF_ZERO_TWO_SPAWN_EGG = register("soul_of_zero_two_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.SOUL_OF_ZERO_TWO.get())));
		ABANDONED_JUKEBOX = block(ZingsProjectRedHornModBlocks.ABANDONED_JUKEBOX);
		ABADONED_CHISELED_BOOKSHELF = block(ZingsProjectRedHornModBlocks.ABADONED_CHISELED_BOOKSHELF);
		PRISMAX = block(ZingsProjectRedHornModBlocks.PRISMAX);
		WARP_GATE = block(ZingsProjectRedHornModBlocks.WARP_GATE);
		JIAN_BANNER_PATTERN = register("jian_banner_pattern", JianBannerPatternItem::new);
		SOUL_OF_HIRO_SPAWN_EGG = register("soul_of_hiro_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.SOUL_OF_HIRO.get())));
		SOULESS_HIRO_SPAWN_EGG = register("souless_hiro_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.SOULESS_HIRO.get())));
		ZERO_THREE_SPAWN_EGG = register("zero_three_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.ZERO_THREE.get())));
		ZERO_FOUR_SPAWN_EGG = register("zero_four_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.ZERO_FOUR.get())));
		THE_BEAST_AND_THE_PRINCE_BOOK = block(ZingsProjectRedHornModBlocks.THE_BEAST_AND_THE_PRINCE_BOOK);
		GREENHOUSE_LAMP = block(ZingsProjectRedHornModBlocks.GREENHOUSE_LAMP);
		GREENHOUSE_LAMP_ON = block(ZingsProjectRedHornModBlocks.GREENHOUSE_LAMP_ON);
		CHISELED_ZERONIUM = block(ZingsProjectRedHornModBlocks.CHISELED_ZERONIUM, new Item.Properties().fireResistant());
		CHISELED_HIRONIUM = block(ZingsProjectRedHornModBlocks.CHISELED_HIRONIUM, new Item.Properties().fireResistant());
		HIRONIUM_LADDER = block(ZingsProjectRedHornModBlocks.HIRONIUM_LADDER);
		ZERONIUM_LADDER = block(ZingsProjectRedHornModBlocks.ZERONIUM_LADDER);
		ZERONIUM_TILES = block(ZingsProjectRedHornModBlocks.ZERONIUM_TILES, new Item.Properties().fireResistant());
		HIRONIUM_TILES = block(ZingsProjectRedHornModBlocks.HIRONIUM_TILES, new Item.Properties().fireResistant());
		CHLOROPHYTUM_PURPLE_DYE = register("chlorophytum_purple_dye", ChlorophytumPurpleDyeItem::new);
		ARGENTEA_PINK_DYE = register("argentea_pink_dye", ArgenteaPinkDyeItem::new);
		GENISTA_GREEN_DYE = register("genista_green_dye", GenistaGreenDyeItem::new);
		DELPHINIUM_BLUE_DYE = register("delphinium_blue_dye", DelphiniumBlueDyeItem::new);
		STRELITZIA_RED_DYE = register("strelitzia_red_dye", StrelitziaRedDyeItem::new);
		DARLING_BLUE_DYE = register("darling_blue_dye", DarlingBlueDyeItem::new);
		DARLING_RED_DYE = register("darling_red_dye", DarlingRedDyeItem::new);
		DARLING_RED_WOOL = block(ZingsProjectRedHornModBlocks.DARLING_RED_WOOL);
		DARLING_BLUE_WOOL = block(ZingsProjectRedHornModBlocks.DARLING_BLUE_WOOL);
		ICHIGONIUM = register("ichigonium", IchigoniumItem::new);
		ICHIGONIUM_INGOT = register("ichigonium_ingot", IchigoniumIngotItem::new);
		ICHIGONIUM_ARMOR_HELMET = register("ichigonium_armor_helmet", IchigoniumArmorItem.Helmet::new);
		ICHIGONIUM_ARMOR_CHESTPLATE = register("ichigonium_armor_chestplate", IchigoniumArmorItem.Chestplate::new);
		ICHIGONIUM_ARMOR_LEGGINGS = register("ichigonium_armor_leggings", IchigoniumArmorItem.Leggings::new);
		ICHIGONIUM_ARMOR_BOOTS = register("ichigonium_armor_boots", IchigoniumArmorItem.Boots::new);
		ICHIGONIUM_SWORD = register("ichigonium_sword", IchigoniumSwordItem::new);
		ICHIGONIUM_AXE = register("ichigonium_axe", IchigoniumAxeItem::new);
		ICHIGONIUM_HOE = register("ichigonium_hoe", IchigoniumHoeItem::new);
		ICHIGONIUM_SHOVEL = register("ichigonium_shovel", IchigoniumShovelItem::new);
		ICHIGONIUM_PICKAXE = register("ichigonium_pickaxe", IchigoniumPickaxeItem::new);
		BLOCK_OF_ICHIGONIUM = block(ZingsProjectRedHornModBlocks.BLOCK_OF_ICHIGONIUM, new Item.Properties().fireResistant());
		ICHIGONIUM_BRICKS = block(ZingsProjectRedHornModBlocks.ICHIGONIUM_BRICKS);
		ICHIGONIUM_ORE = block(ZingsProjectRedHornModBlocks.ICHIGONIUM_ORE);
		DEEPSLATE_ICHIGONIUM_ORE = block(ZingsProjectRedHornModBlocks.DEEPSLATE_ICHIGONIUM_ORE);
		ICHIGO_TINTED_GLASS = block(ZingsProjectRedHornModBlocks.ICHIGO_TINTED_GLASS);
		ICHIGONIUM_BARS = block(ZingsProjectRedHornModBlocks.ICHIGONIUM_BARS);
		ICHIGONIUM_TORCH = block(ZingsProjectRedHornModBlocks.ICHIGONIUM_TORCH);
		ICHIGONIUM_LANTERN = block(ZingsProjectRedHornModBlocks.ICHIGONIUM_LANTERN);
		ICHIGONIUM_STAIRS = block(ZingsProjectRedHornModBlocks.ICHIGONIUM_STAIRS);
		ICHIGONIUM_SLAB = block(ZingsProjectRedHornModBlocks.ICHIGONIUM_SLAB);
		ICHIGONIUM_WALL = block(ZingsProjectRedHornModBlocks.ICHIGONIUM_WALL);
		ICHIGONIUM_HORN_FRAGMENT = register("ichigonium_horn_fragment", IchigoniumHornFragmentItem::new);
		ICHIGONIUM_LADDER = block(ZingsProjectRedHornModBlocks.ICHIGONIUM_LADDER);
		ICHIGONIUM_TILES = block(ZingsProjectRedHornModBlocks.ICHIGONIUM_TILES, new Item.Properties().fireResistant());
		ICHIGO_SPAWN_EGG = register("ichigo_spawn_egg", properties -> new SpawnEggItem(properties.spawnEgg(ZingsProjectRedHornModEntities.ICHIGO.get())));
		ZERO_ARMOR_TRIM_SMITHING_TABLE = register("zero_armor_trim_smithing_table", ZeroArmorTrimSmithingTableItem::new);
		ZERO_TWO_HEADBAND = register("zero_two_headband", ZeroTwoHeadbandItem::new);
		ONIUM = register("onium", OniumItem::new);
		ONIUM_ORE = block(ZingsProjectRedHornModBlocks.ONIUM_ORE);
		DEEPSLATE_ONIUM_ORE = block(ZingsProjectRedHornModBlocks.DEEPSLATE_ONIUM_ORE);
		ZERO_CRYSTAL = block(ZingsProjectRedHornModBlocks.ZERO_CRYSTAL);
		HIRO_CRYSTAL = block(ZingsProjectRedHornModBlocks.HIRO_CRYSTAL);
		ICHIGO_CRYSTAL = block(ZingsProjectRedHornModBlocks.ICHIGO_CRYSTAL);
		DRAGONRAGE_BERRY = register("dragonrage_berry", DragonrageBerryItem::new);
		TOXIC_DRAGONRAGE_BERRY = register("toxic_dragonrage_berry", ToxicDragonrageBerryItem::new);
		DIAMOND_DRAGONRAGE_BERRY = register("diamond_dragonrage_berry", DiamondDragonrageBerryItem::new);
		FERROUS_MINT_SUGAR = register("ferrous_mint_sugar", FerrousMintSugarItem::new);
		FERROUS_MINT_DYE = register("ferrous_mint_dye", FerrousMintDyeItem::new);
		STRIPPED_POPLARAX_LOG = block(ZingsProjectRedHornModBlocks.STRIPPED_POPLARAX_LOG);
		POPLARAX_LOG = block(ZingsProjectRedHornModBlocks.POPLARAX_LOG);
		POPLARAX_PLANKS = block(ZingsProjectRedHornModBlocks.POPLARAX_PLANKS);
		POPLARAX_SLAB = block(ZingsProjectRedHornModBlocks.POPLARAX_SLAB);
		POPLARAX_STAIRS = block(ZingsProjectRedHornModBlocks.POPLARAX_STAIRS);
		POPLARAX_FENCE = block(ZingsProjectRedHornModBlocks.POPLARAX_FENCE);
		POPLARAX_FENCE_GATE = block(ZingsProjectRedHornModBlocks.POPLARAX_FENCE_GATE);
		POPLARAX_BUTTON = block(ZingsProjectRedHornModBlocks.POPLARAX_BUTTON);
		POPLARAX_PRESSURE_PLATE = block(ZingsProjectRedHornModBlocks.POPLARAX_PRESSURE_PLATE);
		POPLARAX_DOOR = doubleBlock(ZingsProjectRedHornModBlocks.POPLARAX_DOOR);
		POPLARAX_TRAPDOOR = block(ZingsProjectRedHornModBlocks.POPLARAX_TRAPDOOR);
		POPLARAX_SIGN = signBlock(ZingsProjectRedHornModBlocks.POPLARAX_SIGN, ZingsProjectRedHornModBlocks.POPLARAX_WALL_SIGN);
		BLUE_POPLARAX_LEAVES = block(ZingsProjectRedHornModBlocks.BLUE_POPLARAX_LEAVES);
		INDIGO_POPLARAX_LEAVES = block(ZingsProjectRedHornModBlocks.INDIGO_POPLARAX_LEAVES);
		PURPLE_POPLARAX_LEAVES = block(ZingsProjectRedHornModBlocks.PURPLE_POPLARAX_LEAVES);
		POPLARAX_SAPLING = block(ZingsProjectRedHornModBlocks.POPLARAX_SAPLING);
		STRIPPED_FERROROCK_WILLOW_LOG = block(ZingsProjectRedHornModBlocks.STRIPPED_FERROROCK_WILLOW_LOG);
		FERROROCK_WILLOW_LOG = block(ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_LOG);
		FERROROCK_WILLOW_PLANKS = block(ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_PLANKS);
		FERROROCK_WILLOW_SLAB = block(ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_SLAB);
		FERROROCK_WILLOW_STAIRS = block(ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_STAIRS);
		FERROROCK_WILLOW_FENCE = block(ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_FENCE);
		FERROROCK_WILLOW_FENCE_GATE = block(ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_FENCE_GATE);
		FERROROCK_WILLOW_BUTTON = block(ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_BUTTON);
		FERROROCK_WILLOW_PRESSURE_PLATE = block(ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_PRESSURE_PLATE);
		FERROROCK_WILLOW_DOOR = doubleBlock(ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_DOOR);
		FERROROCK_WILLOW_TRAPDOOR = block(ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_TRAPDOOR);
		FERROROCK_WILLOW_SIGN = signBlock(ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_SIGN, ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_WALL_SIGN);
		FERROROCK_WILLOW_BOAT = register("ferrorock_willow_boat", properties -> new BoatItem(ZingsProjectRedHornModEntities.FERROROCK_WILLOW_BOAT.get(), properties.stacksTo(1)));
		FERROROCK_WILLOW_BOAT_WITH_CHEST = register("ferrorock_willow_boat_with_chest", properties -> new BoatItem(ZingsProjectRedHornModEntities.FERROROCK_WILLOW_BOAT_WITH_CHEST.get(), properties.stacksTo(1)));
		FERROROCK_WILLOW_LEAVES = block(ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_LEAVES);
		FERROROCK_WILLOW_SAPLING = block(ZingsProjectRedHornModBlocks.FERROROCK_WILLOW_SAPLING);
		STRIPPED_ZERO_PLATEA_LOG = block(ZingsProjectRedHornModBlocks.STRIPPED_ZERO_PLATEA_LOG);
		ZERO_PLATEA_LOG = block(ZingsProjectRedHornModBlocks.ZERO_PLATEA_LOG);
		ZERO_PLATEA_PLANKS = block(ZingsProjectRedHornModBlocks.ZERO_PLATEA_PLANKS);
		ZERO_PLATEA_SLAB = block(ZingsProjectRedHornModBlocks.ZERO_PLATEA_SLAB);
		ZERO_PLATEA_STAIRS = block(ZingsProjectRedHornModBlocks.ZERO_PLATEA_STAIRS);
		ZERO_PLATEA_FENCE = block(ZingsProjectRedHornModBlocks.ZERO_PLATEA_FENCE);
		ZERO_PLATEA_FENCE_GATE = block(ZingsProjectRedHornModBlocks.ZERO_PLATEA_FENCE_GATE);
		ZERO_PLATEA_BUTTON = block(ZingsProjectRedHornModBlocks.ZERO_PLATEA_BUTTON);
		ZERO_PLATEA_PRESSURE_PLATE = block(ZingsProjectRedHornModBlocks.ZERO_PLATEA_PRESSURE_PLATE);
		ZERO_PLATEA_DOOR = doubleBlock(ZingsProjectRedHornModBlocks.ZERO_PLATEA_DOOR);
		ZERO_PLATEA_TRAPDOOR = block(ZingsProjectRedHornModBlocks.ZERO_PLATEA_TRAPDOOR);
		ZERO_PLATEA_SIGN = signBlock(ZingsProjectRedHornModBlocks.ZERO_PLATEA_SIGN, ZingsProjectRedHornModBlocks.ZERO_PLATEA_WALL_SIGN);
		ZERO_PLATEA_RAFT = register("zero_platea_raft", properties -> new BoatItem(ZingsProjectRedHornModEntities.ZERO_PLATEA_RAFT.get(), properties.stacksTo(1)));
		ZERO_PLATEA_RAFT_WITH_CHEST = register("zero_platea_raft_with_chest", properties -> new BoatItem(ZingsProjectRedHornModEntities.ZERO_PLATEA_RAFT_WITH_CHEST.get(), properties.stacksTo(1)));
		ZERO_PLATEA_LEAVES = block(ZingsProjectRedHornModBlocks.ZERO_PLATEA_LEAVES);
		XENONIC_SULFUR = block(ZingsProjectRedHornModBlocks.XENONIC_SULFUR);
		DRAGONRAGE_FERN = doubleBlock(ZingsProjectRedHornModBlocks.DRAGONRAGE_FERN);
		XENONIC_SULFUR_DIAMOND_ORE = block(ZingsProjectRedHornModBlocks.XENONIC_SULFUR_DIAMOND_ORE);
		BLUE_OBSIDIAN = block(ZingsProjectRedHornModBlocks.BLUE_OBSIDIAN);
		FERROUS_MINT_MOSS = block(ZingsProjectRedHornModBlocks.FERROUS_MINT_MOSS);
		GUTEN_CORAL = block(ZingsProjectRedHornModBlocks.GUTEN_CORAL);
		GUTEN_CORAL_BLOCK = block(ZingsProjectRedHornModBlocks.GUTEN_CORAL_BLOCK);
		XENON = register("xenon", XenonItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, Item.Properties::new);
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), () -> properties);
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new DoubleHighBlockItem(block.get(), prop), () -> properties);
	}

	private static DeferredItem<Item> signBlock(DeferredHolder<Block, Block> block, DeferredHolder<Block, Block> wallBlock) {
		return signBlock(block, wallBlock, new Item.Properties());
	}

	private static DeferredItem<Item> signBlock(DeferredHolder<Block, Block> block, DeferredHolder<Block, Block> wallBlock, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new SignItem(block.get(), wallBlock.get(), prop), () -> properties);
	}
}